project_id = "qvhwvegvjmxfjrtbibpd"

[functions.notify-competitive-exams]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
